export const projects = [
  {
    name: "Adify",
    type: "MobileApp",
    tech: [
      "ReactNative",
      "TypeScript",
      "Firebase",
      "ReduxToolkit",
      "JEST",
      "GoogleMaps",
    ],
    img: require("../../assets/adify.png"),
    link: "https://play.google.com/store/apps/details?id=com.admybrand.adify&hl=en_US&gl=US",
    desc: "It's a ad agency related application where we can reach out to them to advertise about our products and we can select the type of advertisement from there (ads, banners etc)",
  },
  {
    name: "AdmyBrand",
    type: "WebApp",
    tech: [
      "ReactJs",
      "NextJs",
      "TypeScript",
      "ReduxToolkit",
      "JEST",
      "GoogleMaps",
    ],
    img: require("../../assets/amb.png"),
    link: "https://in.admybrand.com/",
    desc: "It's a ad agency related application where we can reach out to them to advertise about our product",
  },
  {
    name: "Gyaanbee",
    type: "MobileApp",
    tech: ["ReactNative", "JavaScript", "Firebase"],
    img: require("../../assets/gyanbee.png"),
    link: "https://play.google.com/store/apps/details?id=com.gyaanbee.neet&hl=en_US&gl=US",
    desc: "It's a quiz application mainly focuses on providing knowledge to students and conducts tornaments",
  },
  {
    name: "CryptoSmartLife",
    type: "MobileApp",
    tech: [
      "ReactNative",
      "JavaScript",
      "AWS Cognito",
      "ReduxToolkit",
      "Svg Graphs",
    ],
    img: require("../../assets/csl.png"),
    link: "https://play.google.com/store/apps/details?id=com.cryptosmartlife",
    desc: "This app provides a platform to invest and sell cryto coins directly without third party intervention where we can select the coins in the form of baskets and can invest based on the risk management provided by block chain. We can even save money in the form of crypto and do this on monthly basis. This app even provides feature to sell our crypto.",
  },
  {
    name: "Elanco",
    type: "WebApp",
    tech: ["ReactJs", "NextJs", "TailwindCSS"],
    img: require("../../assets/elanco.png"),
    link: "https://www.elanco.com/en-us",
    desc: "American pet health care related website. In this application, I mainly focused on making this website responsive to all platforms and making it browser compatible",
  },
  {
    name: "HDFC MB Rewritte",
    type: "MobileApp",
    tech: ["ReactNative", "TypeScript", "ReduxToolkit", "JEST"],
    // img: require("../../assets/adify.png"),
    // link: "https://play.google.com/store/apps/details?id=com.admybrand.adify&hl=en_US&gl=US",
    desc: "This app is redesigning of the HDFC bank's application where I got a change to work on deposits section of the app, P.S: can't provide images because it's confidential",
  },
  {
    name: "TYBU",
    type: "MobileApp",
    tech: ["ReactNative", "JavaScript", "ReduxToolkit", "Image procession"],
    // img: require("../../assets/adify.png"),
    // link: "https://play.google.com/store/apps/details?id=com.admybrand.adify&hl=en_US&gl=US",
    desc: "It's an inventory management to manage tyres that are present with TyreBuzz company, in this app admin can create branches and users and can sell the stock from it and can keep a record it ",
  },
  {
    name: "DevLabs",
    type: "WebApp",
    tech: ["NextJS", "JavaScript", "TailwindCSS", "Payment Gateway"],
    img: require("../../assets/devlabs.png"),
    link: "https://devlabs-fe.antino.ca/",
    desc: "It's an online learning platform which is similar to udemy etc",
  },
];
